name: Main Service CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🍀 JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🍀 application.yml 설정
        run: |
          cd ./src/main
          mkdir resources
          cd ./resources
          touch ./application.yml
          echo "$APPLICATION_MAIN" > ./application.yml
        env:
          APPLICATION_MAIN: ${{ secrets.APPLICATION_MAIN }}

      - name: 🍀 gradle build를 위한 권한 설정
        run: |
          chmod +x gradlew

      - name: 🍀 gradle build
        run: |
          ./gradlew build -x test

      - name: 🍀 docker image build 후 docker hub에 push
        run: |
          docker login -u ${{ secrets.MAIN_DOCKER_USERNAME }} -p ${{ secrets.MAIN_DOCKER_PASSWORD }}
          docker build -t ${{ secrets.MAIN_DOCKER_REPOSITORY }}/${{ secrets.MAIN_DOCKER_IMAGE }} .
          docker push ${{ secrets.MAIN_DOCKER_REPOSITORY }}/${{ secrets.MAIN_DOCKER_IMAGE }}

      - name: 🍀 deploy.sh 파일을 EC2 ncloud server로 전달
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.NCLOUD_SERVER_USERNAME }}
          host: ${{ secrets.NCLOUD_SERVER_IP }}
          key: ${{ secrets.NCLOUD_SERVER_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "/home"

      - name: 🍀 docker-compose.yml 파일을 ncloud server로 전송
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.NCLOUD_SERVER_USERNAME }}
          host: ${{ secrets.NCLOUD_SERVER_IP }}
          key: ${{ secrets.NCLOUD_SERVER_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "/home"

      - name: 🍀 docker hub 에서 pull 후 deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.NCLOUD_SERVER_USERNAME }}
          host: ${{ secrets.NCLOUD_SERVER_IP }}
          key: ${{ secrets.NCLOUD_SERVER_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.MAIN_DOCKER_REPOSITORY }}/${{ secrets.MAIN_DOCKER_IMAGE }}
            chmod 777 ./scripts/deploy.sh
            cp ./scripts/deploy.sh ./deploy.sh
            ./deploy.sh
            docker image prune -f